baseURL = "https://sidathasiri.github.io/"
languageCode = "en-us"
title = "Hello"
theme = "hugo-theme-cleanwhite"
paginate = 5 #frontpage pagination

[params]
  header_image = "img/header_image.jpeg"
  SEOTitle = "Sidath Asiri"
  slogan = "Welcome to my Personal Blog"
  sidebar_about_description = "Technical Lead"
  [params.social]
  email          = "sidathasiri@gmail.com"
  linkedin       = "https://www.linkedin.com/in/sidath-asiri"

  [[params.addtional_menus]]
  title =  "About"
  href =  "/about/"
